import {Fragment} from 'react'

/*Se crea un componente funcional, en este caso el componente sera exportado y se va a llamar About
y solo va a retornar un About */
/*El import fragment sirve para meter todo el codigo html y que no lo tome como error por el formato
jsx y evitar crear un div que almacene todo, al final Fragment es como un elemento que no es tenido
en cuenta en el navegador */
export const About = () => (
    <Fragment>
        <h1>About</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa explicabo libero iure corrupti, in quidem quis atque natus, magni eveniet ipsam cupiditate autem quod similique commodi sequi quisquam expedita! Qui tenetur expedita dolorum repellendus, aperiam dolore soluta pariatur blanditiis voluptatum rem ipsam itaque explicabo consequatur eos quidem impedit laborum, delectus debitis quod animi! Incidunt ex explicabo minima dolorem, repellat labore? Omnis, numquam! Aperiam natus repellendus, deserunt at minus dolore? Asperiores, accusamus. Vitae itaque quae repellat dolore porro harum eum neque officiis quos quis aliquam obcaecati, consectetur architecto asperiores, numquam modi? Omnis et, vero quo est facilis quibusdam laborum id amet doloribus quasi nulla distinctio accusantium excepturi impedit obcaecati commodi accusamus adipisci quisquam veniam culpa, sapiente quaerat delectus labore. Eaque, quia maiores. Quaerat, totam provident? Voluptatum dignissimos quos aperiam, veritatis cumque distinctio dolore molestiae incidunt impedit consectetur vel animi temporibus placeat praesentium repellat debitis a fugit cum, illo ullam nesciunt laudantium nam! Voluptate debitis nihil maxime molestias sunt doloremque, vitae magnam expedita incidunt quo, delectus nam ipsam tenetur enim obcaecati non quibusdam quasi quas eligendi necessitatibus illo? Voluptatum quidem totam optio quia est! Iusto, nobis! Beatae mollitia rerum ea dicta doloribus nostrum veniam architecto non at enim, debitis consequatur modi suscipit eum voluptatibus ad distinctio, voluptatem ipsum impedit iste nemo dolorum sequi! Suscipit magni impedit molestiae ut laborum, quasi ab corporis quis dicta praesentium, ex iusto ullam quas magnam quos pariatur iste qui perspiciatis in, minus amet natus beatae. Iusto odio sapiente dolorum natus eos, animi iure numquam fugiat, sint, unde ea? Accusantium voluptatibus beatae a esse autem dignissimos officiis perferendis vitae qui quis, sint tempore, iste impedit molestias voluptates commodi! Tenetur tempore ducimus temporibus sapiente quam! Omnis consequuntur nulla nobis eligendi sit. Voluptatibus cum minus eius maiores reprehenderit, nisi quidem quas! Cum corporis pariatur molestiae velit odit deserunt nemo ex.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa explicabo libero iure corrupti, in quidem quis atque natus, magni eveniet ipsam cupiditate autem quod similique commodi sequi quisquam expedita! Qui tenetur expedita dolorum repellendus, aperiam dolore soluta pariatur blanditiis voluptatum rem ipsam itaque explicabo consequatur eos quidem impedit laborum, delectus debitis quod animi! Incidunt ex explicabo minima dolorem, repellat labore? Omnis, numquam! Aperiam natus repellendus, deserunt at minus dolore? Asperiores, accusamus. Vitae itaque quae repellat dolore porro harum eum neque officiis quos quis aliquam obcaecati, consectetur architecto asperiores, numquam modi? Omnis et, vero quo est facilis quibusdam laborum id amet doloribus quasi nulla distinctio accusantium excepturi impedit obcaecati commodi accusamus adipisci quisquam veniam culpa, sapiente quaerat delectus labore. Eaque, quia maiores. Quaerat, totam provident? Voluptatum dignissimos quos aperiam.</p>
    </Fragment>
)